INSERT INTO products (
    id, 
    name, 
    description, 
    price, 
    category, 
    company, 
    imgUrl, 
    components, 
    createdAt, 
    updatedAt
) VALUES (
    12, 
    'Mini Tractor', 
    'The smallest in the tractor family, mini tractors are designed for light-duty tasks and are perfect for managing small plots of land. With horsepower (HP) usually ranging from 15 to 30 HP.', 
    '750.00', 
    'Home utensils', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1716990360686-image.jpg', 
    '[{\"name\":\"Main Trailer\",\"price\":\"200.00\",\"description\":\"This is the main trailer component.\"},{\"name\":\"This is another optional detail.\",\"price\":\"50.00\",\"description\":\"\"},{\"name\":\"For the last, very optional.\",\"price\":\"70.00\",\"description\":\"\"}]', 
    '2024-05-29 13:46:00', 
    '2024-05-29 20:43:53'
), 
(
    13, 
    'VASCA POSTERIORE TKE T5', 
    'Ribaltabile posteriore con cilindro di sollevamento frontale;\\ncassa autoportante poligonale;\\nsponda posteriore apribile idraulicamente con Sistema DUAL – CONTROL;\\nsia BASCULANTE che ad ALA DI GABBIANO ad una altezza di 700 mm\\noltre il filo superior sponda;\\nsistema di utilizzo e sicurezza conformi alle direttive macchine;\\nvelocità di sollevamento 25 sec x1000 giri/min;\\nimpianto idraulico a bassa pressione;\\nCilindro idraulico telescopico a 4 sfili di sollevamento frontale\\ncon Sistema di apertura idraulico della sponda posteriorre;\\nspessore fondo: basic 6 mm;\\nspessore sponde: basic 4 mm;\\ncassetta porta attrezzi inox montato lateralmente al contro telaio;\\ncassetta porta attrezzi supplementare inox media;\\nparafanghi singoli posteriori in PVC rinforzato in kit;\\nprotezione salva cabina predisposto per copri carico;\\napertura sponda posteriore idraulica ad ala di gabbiano con Sistema dual – control;\\nsabbiatura allestimento;\\nstrisce riflettenti laterali e posteriori;\\nbarra para incastro omologata manuale;\\nprolunga scarico in finitrice smontabile;\\nverniciatura monocolore con serigrafie standard adesive;\\nprotezione laterali per il veicolo in abbinamento;\\ncopricarico – spinnaker a commando elettrico con telecomando.', 
    '47730.00', 
    'Vasche', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1717066757413-image.jpg', 
    '[{\"name\":\"MOTO VIBRATORE ELETTRICO CON COMANDO IN CABINA\",\"price\":\"7650.00\",\"description\":\"\"},{\"name\":\"BARRA PARAINCASTRO CON SOLLEVAMENTO IDRAULICO\",\"price\":\"13600.00\",\"description\":\"\"},{\"name\":\"CASSETTA ATTREZZI INOX GRANDE SUPPLEMENTARE\",\"price\":\"4420.00\",\"description\":\"\"},{\"name\":\"SERBATOIO GASOLIO SUPPLEMENTARE\",\"price\":\"4500.00\",\"description\":\"\"},{\"name\":\"MAIALINO PER GASOLIO\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"TANICA LAVA MANI DA 25 LT\",\"price\":\"1530.00\",\"description\":\"\"}]', 
    '2024-05-30 10:59:17', 
    '2024-05-31 05:53:29'
), 
(
    14, 
    'BETONIERA CIFA RY 1300', 
    'Betoniera RY 1300\\nCapacità nominale: 12 mc\\nVolume geometrico:17.4mc\\nVelocità di rotazione:14 rpm\\nDiametro tamburo: 2350 mm\\nn. 4 rulli\\nContalitri 0-500\\nDOTAZIONI DI SERIE:\\nTelaio di base diritto o sagomato (30MnB5)\\nProtezione antiusura eliche 25x8 mm\\nDue passi d’uomo\\nDoppi rulli di rotolamento diam. 250 mm con supporto a bilancino\\nCanala di scarico ribaltabile 1500mm + 900mm\\nVersione con serbatoio acqua non pressurizzato:\\n• Serbatoio acqua 1200 litri\\n• Pompa alza canala idraulica\\n• Scambiatore di calore\\nContatore acqua\\nDue lance di lavaggio (una a terra con innesto rapido, una sulla pedana scaletta)\\nInnesto rapido acqua da ambo i lati\\nManometro rilevamento consistenza calcestruzzo\\nDue tronchi canala supplementari, con supporti di fissaggio su controtelaio\\nEliche sbordate, a quattro principi nel punto di scarico\\nLamiere antiusura su tramoggia di carico e canala di scarico\\nUnità completamente sabbiata e protetta con fondo antiruggine\\nLampeggiante posteriore\\nParafanghi monoasse in plastica con paraspruzzi CIFA\\nPompa acqua e cilindro alza canala, azionati idraulicamente attraverso un distributore\\nBarra posteriore paraincastro ribaltabile omologata\\nPulsanti di emergenza Start/Stop per motore automezzo\\n* Un faro illuminazione a led posteriore\\n* Telecamera posteriore con monitor in cabina\\n* rispetta EN 12609\\n Tamburo ed eliche\\nIl tamburo è progettato secondo le specifiche internazionali e la norma DIN 459. Acciaio speciale resistente all’usura (450HB) nel tamburo (4 mm) e nelle eliche (3 mm) per massimizzare la durata\\ndella betoniera.', 
    '45150.00', 
    'Cifa', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1717135133154-image.jpg', 
    '[{\"name\":\"BETONIERA MONTATA SU CAMION DA CIFA\",\"price\":\"57600.00\",\"description\":\"Nota: nella configurazione montata su automezzo sono inclusi,\\n- Montaggio su automezzo\\n- Parafanghi singoli in plastica (BPLTAN)\\n- Cardano (BCARDA)\\n- Ancoraggi inclusi bulloni (BANCBU)\\n- parametrizzazione (BSI)\\n- Barre paraincastro (BRIBAL)\\n- Barre paraciclisti (BCICLI)\\n- verniciatura ad un colore (BMOCOL)\\n- Luci laterali - Omologata ECC per circolazione stradale (BLULAT)\\n\"},{\"name\":\"BETONIERE PER SISTEMA SCARRABILE\",\"price\":\"0.00\",\"description\":\"Nota:\\n- SONO ESCLUSI dalla fornitura: barra paraincastro posteriore, barre paraciclisti, parafanghi in plastica tandem posteriore, collaudo su autoveicolo, collaudo per immatricolazione circolazione stradale;\\n- NOTA: l\'altezza massimo del filo superiore del telaio del veicolo, compreso il telaio dell\'attrezzatura scarrabile, non deve superare 1200 mm da terra\\n\"},{\"name\":\"Collaudo autobetoniera - mercato Italia PREZZO NETTO\",\"price\":\"8400.00\",\"description\":\"\"},{\"name\":\"Omologazione europea (DEKRA - non necessaria per mercato Italia)\",\"price\":\"14600.00\",\"description\":\"\"},{\"name\":\"CIFA VISTA 4.0 Ready [Disponibile solo per versioni CSD Advanced]\",\"price\":\"60600.00\",\"description\":\"\"},{\"name\":\"CIFA VISTA - Installazione e due anni di licenza per il sistema di monitoraggio da remoto (Disponibile solo con CSD Advanced)\",\"price\":\"42500.00\",\"description\":\"\"},{\"name\":\"Parafango singolo in plastica + paraspruzzi per tandem posteriore\",\"price\":\"10900.00\",\"description\":\"\"},{\"name\":\"Parafango in acciaio + paraspruzzi per tandem posteriore\",\"price\":\"10900.00\",\"description\":\"\"}]', 
    '2024-05-31 05:58:53', 
    '2024-05-31 05:58:53'
), 
(
    15, 
    'VASCA POSTERIORE TKE S5', 
    'Ribaltabile posteriore con cilindro di sollevamento frontale;\\ncassa autoportante poligonale;\\nsponda posteriore apribile idraulicamente con Sistema DUAL – CONTROL;\\nsia BASCULANTE che ad ALA DI GABBIANO ad una altezza di 700 mm\\noltre il filo superior sponda;\\nsistema di utilizzo e sicurezza conformi alle direttive macchine;\\nvelocità di sollevamento 25 sec x1000 giri/min;\\nimpianto idraulico a bassa pressione;\\nCilindro idraulico telescopico a 4 sfili di sollevamento frontale\\ncon Sistema di apertura idraulico della sponda posteriorre;\\nspessore fondo: basic 6 mm;\\nspessore sponde: basic 4 mm;\\ncassetta porta attrezzi inox montato lateralmente al contro telaio;\\ncassetta porta attrezzi supplementare inox media;\\nparafanghi singoli posteriori in PVC rinforzato in kit;\\nprotezione salva cabina predisposto per copri carico;\\napertura sponda posteriore idraulica ad ala di gabbiano con Sistema dual – control;\\nsabbiatura allestimento;\\nstrisce riflettenti laterali e posteriori;\\nbarra para incastro omologata manuale;\\nprolunga scarico in finitrice smontabile;\\nverniciatura monocolore con serigrafie standard adesive;\\npinne verniciate acciaio;\\nprotezione laterali per il veicolo in abbinamento;\\ncopricarico – spinnaker a commando elettrico con telecomando.', 
    '42300.00', 
    'Vasche', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1717139362207-image.jpg', 
    '[{\"name\":\"MOTO VIBRATORE ELETTRICO CON COMANDO IN CABINA\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"BARRA PARAINCASTRO CON SOLLEVAMENTO IDRAULICO\",\"price\":\"1360.00\",\"description\":\"\"},{\"name\":\"CASSETTA ATTREZZI INOX GRANDE SUPPLEMENTARE\",\"price\":\"442.00\",\"description\":\"\"},{\"name\":\"SERBATOIO GASOLIO SUPPLEMENTARE\",\"price\":\"450.00\",\"description\":\"\"},{\"name\":\"MAIALINO PER GASOLIO\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"TANICA LAVA MANI DA 25 LT\",\"price\":\"153.00\",\"description\":\"\"}]', 
    '2024-05-31 07:09:22', 
    '2024-05-31 07:29:30'
), 
(
    16, 
    'VASCA POSTERIORE TKE P6 EVO', 
    'Ribaltabile posteriore con cilindro di sollevamento frontale;\\ncassa autoportante poligonale;\\nsponda posteriore apribile idraulicamente con Sistema DUAL – CONTROL;\\nsia BASCULANTE che ad ALA DI GABBIANO ad una altezza di 700 mm\\noltre il filo superior sponda;\\nsistema di utilizzo e sicurezza conformi alle direttive macchine;\\nvelocità di sollevamento 25 sec x1000 giri/min;\\n\\nimpianto idraulico a bassa pressione;\\nCilindro idraulico telescopico a 4 sfili di sollevamento frontale\\ncon Sistema di apertura idraulico della sponda posteriorre;\\nspessore fondo: basic 6 mm;\\nspessore sponde: basic 4 mm;\\ncassetta porta attrezzi inox montato lateralmente al contro telaio;\\ncassetta porta attrezzi supplementare inox media;\\nparafanghi singoli posteriori in PVC rinforzato in kit;\\nprotezione salva cabina predisposto per copri carico;\\napertura sponda posteriore idraulica ad ala di gabbiano con Sistema dual – control;\\nsabbiatura allestimento;\\nstrisce riflettenti laterali e posteriori;\\nbarra para incastro omologata manuale;\\nprolunga scarico in finitrice smontabile;\\nverniciatura monocolore con serigrafie standard adesive;\\nprotezione laterali per il veicolo in abbinamento;\\ncopricarico – spinnaker a commando elettrico con telecomando.', 
    '43150.00', 
    'Vasche', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1717140057659-image.jpg', 
    '[{\"name\":\"MOTO VIBRATORE ELETTRICO CON COMANDO IN CABINA\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"BARRA PARAINCASTRO CON SOLLEVAMENTO IDRAULICO\",\"price\":\"1360.00\",\"description\":\"\"},{\"name\":\"CASSETTA ATTREZZI INOX GRANDE SUPPLEMENTARE\",\"price\":\"442.00\",\"description\":\"\"},{\"name\":\"SERBATOIO GASOLIO SUPPLEMENTARE\",\"price\":\"450.00\",\"description\":\"\"},{\"name\":\"MAIALINO PER GASOLIO\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"TANICA LAVA MANI DA 25 LT\",\"price\":\"153.00\",\"description\":\"\"}]', 
    '2024-05-31 07:20:57', 
    '2024-05-31 07:20:57'
), 
(
    17, 
    'VASCA POSTERIORE TKE P6 EXP', 
    'Ribaltabile posteriore con cilindro di sollevamento frontale;\\ncassa autoportante poligonale;\\nsponda posteriore apribile idraulicamente con Sistema DUAL – CONTROL;\\nsia BASCULANTE che ad ALA DI GABBIANO ad una altezza di 700 mm\\noltre il filo superior sponda;\\nsistema di utilizzo e sicurezza conformi alle direttive macchine;\\nvelocità di sollevamento 25 sec x1000 giri/min;\\nimpianto idraulico a bassa pressione;\\nCilindro idraulico telescopico a 4 sfili di sollevamento frontale\\ncon Sistema di apertura idraulico della sponda posteriorre;\\nspessore fondo: basic 6 mm;\\nspessore sponde: basic 4 mm;\\ncassetta porta attrezzi inox montato lateralmente al contro telaio;\\ncassetta porta attrezzi supplementare inox media;\\nparafanghi singoli posteriori in PVC rinforzato in kit;\\nprotezione salva cabina predisposto per copri carico;\\napertura sponda posteriore idraulica ad ala di gabbiano con Sistema dual – control;\\nsabbiatura allestimento;\\nstrisce riflettenti laterali e posteriori;\\nbarra para incastro omologata manuale;\\nprolunga scarico in finitrice smontabile;\\nverniciatura monocolore con serigrafie standard adesive;\\nprotezione laterali per il veicolo in abbinamento;\\ncopricarico – spinnaker a commando elettrico con telecomando.', 
    '43150.00', 
    'Vasche', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1717140310806-image.jpg', 
    '[{\"name\":\"MOTO VIBRATORE ELETTRICO CON COMANDO IN CABINA\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"BARRA PARAINCASTRO CON SOLLEVAMENTO IDRAULICO\",\"price\":\"1360.00\",\"description\":\"\"},{\"name\":\"CASSETTA ATTREZZI INOX GRANDE SUPPLEMENTARE\",\"price\":\"442.00\",\"description\":\"\"},{\"name\":\"SERBATOIO GASOLIO SUPPLEMENTARE\",\"price\":\"450.00\",\"description\":\"\"},{\"name\":\"MAIALINO PER GASOLIO\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"TANICA LAVA MANI DA 25 LT\",\"price\":\"153.00\",\"description\":\"\"}]', 
    '2024-05-31 07:25:10', 
    '2024-05-31 07:25:10'
), 
(
    18, 
    'VASCA POSTERIORE TKE S5 INTERCAMBIABILE', 
    'Ribaltabile posteriore con cilindro di sollevamento frontale;\\ncassa autoportante poligonale;\\nsponda posteriore apribile idraulicamente con Sistema DUAL – CONTROL;\\nsia BASCULANTE che ad ALA DI GABBIANO ad una altezza di 700 mm\\noltre il filo superior sponda;\\nsistema di utilizzo e sicurezza conformi alle direttive macchine;\\nvelocità di sollevamento 25 sec x1000 giri/min;\\nimpianto idraulico a bassa pressione;\\nCilindro idraulico telescopico a 4 sfili di sollevamento frontale\\ncon Sistema di apertura idraulico della sponda posteriorre;\\nspessore fondo: basic 6 mm;\\nspessore sponde: basic 4 mm;\\ncassetta porta attrezzi inox montato lateralmente al contro telaio;\\ncassetta porta attrezzi supplementare inox media;\\nparafanghi singoli posteriori in PVC rinforzato in kit;\\nprotezione salva cabina predisposto per copri carico;\\napertura sponda posteriore idraulica ad ala di gabbiano con Sistema dual – control;\\nsabbiatura allestimento;\\nstrisce riflettenti laterali e posteriori;\\nbarra para incastro omologata manuale;\\nprolunga scarico in finitrice smontabile;\\nverniciatura monocolore con serigrafie standard adesive;\\npinne verniciate acciaio;\\nprotezione laterali per il veicolo in abbinamento;\\ncopricarico – spinnaker a commando elettrico con telecomando.', 
    '42300.00', 
    'Vasche', 
    'sermixer', 
    'http://sermixer.micro-cloud.it:12923/images/1717140504994-image.jpg', 
    '[{\"name\":\"MOTO VIBRATORE ELETTRICO CON COMANDO IN CABINA\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"BARRA PARAINCASTRO CON SOLLEVAMENTO IDRAULICO\",\"price\":\"1360.00\",\"description\":\"\"},{\"name\":\"CASSETTA ATTREZZI INOX GRANDE SUPPLEMENTARE\",\"price\":\"442.00\",\"description\":\"\"},{\"name\":\"SERBATOIO GASOLIO SUPPLEMENTARE\",\"price\":\"450.00\",\"description\":\"\"},{\"name\":\"MAIALINO PER GASOLIO\",\"price\":\"765.00\",\"description\":\"\"},{\"name\":\"TANICA LAVA MANI DA 25 LT\",\"price\":\"153.00\",\"description\":\"\"}]', 
    '2024-05-31 07:28:24', 
    '2024-05-31 07:28:24'
);
